name: Gerar IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia às 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -U yt-dlp

      - name: Criar cookies.txt a partir do segredo
        run: echo "${{ secrets.cookies_txt }}" > cookies.txt

      - name: Executar o script Python
        run: python gerar_iptv.py

      - name: Subir iptv.m3u8 para o repositório
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add iptv.m3u8
          git commit -m "Atualizar iptv.m3u8 automático" || echo "Sem alterações para commit"
          git push





