name: Gerar IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar yt-dlp
      run: pip install -U yt-dlp

    - name: Criar cookies.txt a partir do segredo
      run: echo "${{ secrets.COOKIES_TXT }}" > cookies.txt

    - name: Executar script
      run: python gerar_iptv.py

    - name: Subir iptv.m3u8 para o repositório
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add iptv.m3u8 || true
        git commit -m "Atualização automática do IPTV" || echo "Nada para commitar"
        git push



