name: Gerar IPTV

on:
  workflow_dispatch:

jobs:
  gerar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Restaurar cookies.txt a partir de base64
        run: echo "${{ secrets.COOKIES_B64 }}" | base64 -d > cookies.txt

      - name: Executar script gerar_iptv.py
        run: python gerar_iptv.py

      - name: Confirmar alterações (caso iptv.m3u8 tenha sido gerado)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add iptv.m3u8 || true
          git commit -m "Atualizar iptv.m3u8" || echo "Nada para commitar"
          git push




