name: Gerar IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar yt-dlp
        run: pip install -U yt-dlp

      - name: Restaurar cookies.txt a partir do segredo
        if: ${{ secrets.COOKIES_TXT != '' }}
        run: echo "${{ secrets.COOKIES_TXT }}" > cookies.txt

      - name: Verificar cookies.txt
        run: head -n 5 cookies.txt

      - name: Executar o script
        run: python gerar_iptv.py

      - name: Verificar conteúdo do iptv.m3u8
        run: |
          if [ -s iptv.m3u8 ]; then
            echo "[OK] Arquivo gerado com sucesso:"
            head -n 10 iptv.m3u8
          else
            echo "[ERRO] Arquivo iptv.m3u8 está vazio!"
            exit 1
          fi

      - name: Subir alterações para o repositório
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add iptv.m3u8
          git commit -m "Atualização automática do IPTV"
          git push || echo "Nada a atualizar."

