name: Gerar IPTV

on:
  workflow_dispatch:        # Você pode executar manualmente
  schedule:
    - cron: '0 */6 * * *'   # Executa a cada 6 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar yt-dlp
        run: pip install -U yt-dlp

      - name: Criar cookies.txt (secreto)
        if: secrets.COOKIES_TXT != ''
        run: echo "${{ secrets.COOKIES_TXT }}" > cookies.txt

      - name: Executar gerar_iptv.py
        run: python gerar_iptv.py

      - name: Confirmar e subir alterações
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add iptv.m3u8
          git commit -m "Atualização automática do IPTV"
          git push
